filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /usr/share/elasticsearch/logs/gc.log*
    fields:
      log_type: gc_log 

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info

